### ISSUE TITLE
Moving lisp-invocation to a separate library?

### ISSUE THREAD

**Issue by eudoxia0** [fare/xcvb#4]
I recently wrote a small library that does essentially the same, but then immediately found lisp-invocation. It'd be better for discovery if it was an independent library with its own README.

**Comment by fare** [comment]
It is!
https://gitlab.common-lisp.net/qitab/lisp-invocation
OK, the README is missing — maybe you can contribute it?

**Comment by fare** [comment]
Note that the asdf-tools system in the minimakefile branch of asdf has a few extensions to lisp-invocation for allegro and ecl variants.

**Comment by eudoxia0** [comment]
Ok, I'll write up a brief REAMDE.

**Comment by eudoxia0** [comment]
Since I've been fatally spoiled by GitHub and don't know how to use GitLab I'll just post it here:

# lisp-invocation

lisp-invocation is a small library for starting Lisp processes from Common Lisp.

## Usage

A simple example: Starting an SBCL process, running some code and quitting. We
use [external-program][ext] to run the process.

```lisp
(destructuring-bind (command &rest arguments)
  (let ((code (format nil "(progn (+ 1 1) ~A)"
                      (lisp-invocation:quit-form :code 0 :implementation-type :sbcl))))
    (lisp-invocation:lisp-invocation-arglist :implementation-type :sbcl
                                             :eval code))
  ;; We start the process and return the process object
  (external-program:start command arguments))
```

[ext]: https://github.com/sellout/external-program

## License

Free Software available under an MIT-style license. See LICENSE in the xcbv
project.

Copyright (c) 2008 ITA Software, Inc.  All rights reserved.

**Comment by fare** [comment]
Thanks a lot! I pushed something based on what you offered, except I tweaked it a bit. Enjoy!
